# Generated by Django 5.2.5 on 2025-08-22 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('statement', models.TextField(verbose_name='Enunciado')),
                ('tags', models.CharField(help_text='Tags separadas por vírgula', max_length=255, verbose_name='Tags')),
                ('criteria', models.TextField(help_text='Critérios de avaliação', verbose_name='Critérios')),
                ('judge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Juiz')),
            ],
        ),
    ]
